import {ObjectStatus, ProfileGender, IPlace, IMedia} from "../index.mjs";

export interface IProfile {
  profileID: string,
  uniqRef: string,
  slug: string,
  avatar?: IMedia,
  firstName: string,
  middleName?: string,
  lastName: string,
  dateOfBirth: Date,
  gender?: ProfileGender,
  firstNationality: string,
  secondNationality?: string,
  thirdNationality?: string,
  phoneNumber: string,
  location?: IPlace,
  idCardNumber: string,
  passportNumber: string,
  socialSecurityNumber: string,
  state: ObjectStatus,
  createdAt: Date,
  updatedAt?: Date,
  deletedAt?: Date,
}

export type ProfileInput = {
  profileID: string,
  authorID?: string,
  avatar?: IMedia,
  firstName?: string,
  middleName?: string,
  lastName?: string,
  dateOfBirth?: Date,
  gender?: ProfileGender,
  firstNationality?: string,
  secondNationality?: string,
  thirdNationality?: string,
  phoneNumber?: string,
  location?: IPlace,
  idCardNumber?: string,
  passportNumber?: string,
  socialSecurityNumber?: string,
  state?: ObjectStatus,
}
